// <auto-generated />
using System;
using InventarioApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventarioApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("InventarioApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Equipos electronicos",
                            Nombre = "Electronica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Articulos de oficina",
                            Nombre = "Papeleria"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Equipos de trabajo",
                            Nombre = "Herramientas"
                        });
                });

            modelBuilder.Entity("InventarioApp.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Movimientos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 10,
                            Fecha = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observacion = "Compra inicial",
                            ProductoId = 1,
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            Fecha = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observacion = "Venta cliente A",
                            ProductoId = 1,
                            Tipo = "Salida"
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 5,
                            Fecha = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observacion = "Reposicion",
                            ProductoId = 2,
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            Fecha = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Observacion = "Prestamo interno",
                            ProductoId = 4,
                            Tipo = "Salida"
                        });
                });

            modelBuilder.Entity("InventarioApp.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            FechaRegistro = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Laptop Dell",
                            PrecioUnitario = 15000m,
                            Stock = 8,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            FechaRegistro = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Mouse Logitech",
                            PrecioUnitario = 350m,
                            Stock = 3,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            FechaRegistro = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Resma Papel",
                            PrecioUnitario = 120m,
                            Stock = 50,
                            StockMinimo = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            FechaRegistro = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Taladro Bosch",
                            PrecioUnitario = 2800m,
                            Stock = 2,
                            StockMinimo = 3
                        });
                });

            modelBuilder.Entity("InventarioApp.Models.MovimientoInventario", b =>
                {
                    b.HasOne("InventarioApp.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("InventarioApp.Models.Producto", b =>
                {
                    b.HasOne("InventarioApp.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("InventarioApp.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventarioApp.Models.Producto", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
